FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore -r linux-arm

COPY . ./
RUN dotnet publish -c release -o out -r linux-arm

FROM mcr.microsoft.com/dotnet/core/runtime:3.0-buster-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "Telemetry.dll"]