name: IoT Unit Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "iot/src/**"
      - "shared/src/**"
      - ".github/workflows/iot-test.yml"
  push:
    branches: [main]
    paths:
      - "iot/src/**"
      - "shared/src/**"
      - ".github/workflows/iot-test.yml"
  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.x"
  
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Restore dependencies
        run: |
          dotnet restore iot/src/MeatGeek.IoT.Functions/MeatGeek.IoT.Functions.csproj
          dotnet restore iot/src/MeatGeek.IoT.WorkerApi/MeatGeek.IoT.WorkerApi.csproj
          dotnet restore iot/src/MeatGeek.IoT.Functions.Tests/MeatGeek.IoT.Functions.Tests.csproj
          dotnet restore iot/src/MeatGeek.IoT.WorkerApi.Tests/MeatGeek.IoT.WorkerApi.Tests.csproj
          
      - name: Build projects
        run: |
          dotnet build iot/src/MeatGeek.IoT.Functions/MeatGeek.IoT.Functions.csproj --configuration Release --no-restore
          dotnet build iot/src/MeatGeek.IoT.WorkerApi/MeatGeek.IoT.WorkerApi.csproj --configuration Release --no-restore
          dotnet build iot/src/MeatGeek.IoT.Functions.Tests/MeatGeek.IoT.Functions.Tests.csproj --configuration Release --no-restore
          dotnet build iot/src/MeatGeek.IoT.WorkerApi.Tests/MeatGeek.IoT.WorkerApi.Tests.csproj --configuration Release --no-restore
          
      - name: Run IoT Functions Tests
        run: |
          dotnet test iot/src/MeatGeek.IoT.Functions.Tests/MeatGeek.IoT.Functions.Tests.csproj \
            --configuration Release \
            --no-build \
            --verbosity normal \
            --logger trx \
            --results-directory ./test-results/functions
            
      - name: Run IoT Worker API Tests
        run: |
          dotnet test iot/src/MeatGeek.IoT.WorkerApi.Tests/MeatGeek.IoT.WorkerApi.Tests.csproj \
            --configuration Release \
            --no-build \
            --verbosity normal \
            --logger trx \
            --results-directory ./test-results/worker
            
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./test-results/
          
      - name: Test Summary
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: IoT Unit Test Results
          path: './test-results/**/*.trx'
          reporter: dotnet-trx
          fail-on-error: true