---
name: IoT Edge CI

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - ".github/workflows/iot-edge-ci.yaml"
      - "iot-edge/modules/**"
      - "iot-edge/.env_template"
      - "iot-edge/deployment.template.json"
  workflow_dispatch:

env:
  ACR_IMAGE_PATH_TELEMETRY: ${{ secrets.ACR_LOGIN_SERVER }}/telemetry:1.0.${{ github.run_number }}-amd64
  DOTNET_VERSION: "6.0.x"
  AZURE_RESOURCEGROUP_NAME: "MeatGeek-IoT"
  APP_PACKAGE_PATH: "." # set this to the path to your function app project, defaults to the repository root

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ACR
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: :1.0.${{ github.run_number }}-amd64
          file: ./modules/Telemetry/Dockerfile.amd64
