name: MeatGeek Deploy Sessions Infra
on:
  push:
    branches:
      - main
    paths:
      - "sessions/src/MeatGeek.Sessions.Api"
      - "sessions/src/MeatGeek.Sessions.Services"
      - "sessions/build/build.yaml"
      - "shared/src/*"
      - "shared/build/build.yaml"
      - "!sessions/docs"
      - "!sessions/mkdocs.yml"
      - "!sessions/build/build-docs.yaml"
      - "!.vscode"
env:
  app-name: "meatgeeksessionsapi"
  rg-name: "MeatGeek-Sessions"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore "sessions/src/MeatGeek.Sessions.Api/*.csproj"
      - name: Build
        run: dotnet build --no-restore "sessions/src/MeatGeek.Sessions.Api/*.csproj"
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
