name: MeatGeek Deploy Sessions Infra
on:
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/sessions-resources.yml"
      - "sessions/deploy/*"

jobs:
  deploy-sessions-resources:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.SESSIONS_RG }}
          template: ./sessions/deploy/microservice.bicep
          parameters: kvName=${{ secrets.SHARED_KV }}
            cosmosAccountName=${{ secrets.SHARED_COSMOS }}
            cosmosDatabaseName=${{ secrets.SHARED_COSMOS }}
            sessionsContainerName=${{ secrets.SESSIONS_COSMOS_COLLECTION_NAME }}
            sessionsPartition=${{ secrets.SESSIONS_COSMOS_PARTITION_PATH }}
            iotContainerName=${{ secrets.IOT_COSMOS_COLLECTION_NAME }}
            iotPartition=${{ secrets.IOT_COSMOS_PARTITION_PATH }}

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
