name: MeatGeek Sessions Deploy Sessions Infra
on:
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/sessions-resources.yml"
      - "sessions/deploy/*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.SESSIONS_RG }}
          template: ./sessions/deploy/microservice.json
          # parameters: sqlServerPassword=${{ secrets.SQL_SERVER }}

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
