name: Shared Library Build & Test

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/shared-build-deploy.yml"
      - "shared/src/**"
      - "shared/tests/**"
      - "shared/build/build.yaml"
      - "!shared/docs"
      - "!.vscode"
  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    outputs:
      test-status: ${{ steps.test-execution.outcome }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Restore dependencies
        run: |
          dotnet restore shared/src/MeatGeek.Shared/MeatGeek.Shared.csproj
          dotnet restore shared/tests/MeatGeek.Shared.Tests/MeatGeek.Shared.Tests.csproj
          
      - name: Build projects
        run: |
          dotnet build shared/src/MeatGeek.Shared/MeatGeek.Shared.csproj --configuration Release --no-restore
          dotnet build shared/tests/MeatGeek.Shared.Tests/MeatGeek.Shared.Tests.csproj --configuration Release --no-restore
          
      - name: Run Unit Tests
        id: test-execution
        run: |
          echo "Running Shared Library Tests..."
          dotnet test shared/tests/MeatGeek.Shared.Tests/MeatGeek.Shared.Tests.csproj \
            --configuration Release \
            --no-build \
            --verbosity normal \
            --logger trx \
            --results-directory ./test-results/shared
            
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./test-results/
          
      - name: Test Summary
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Shared Library Test Results
          path: './test-results/**/*.trx'
          reporter: dotnet-trx
          fail-on-error: true

  build-and-package:
    name: Build and Package Library
    runs-on: ubuntu-latest
    needs: test  # ⚠️ CRITICAL: Build only runs if tests pass
    if: success()  # Only run if tests succeed
    
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: "Setup DotNet ${{ env.DOTNET_VERSION }} Environment"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Build Shared Library"
        shell: bash
        run: |
          dotnet build "./shared/src/MeatGeek.Shared" --configuration Release
          
      - name: "Package Library"
        shell: bash
        run: |
          dotnet pack "./shared/src/MeatGeek.Shared/MeatGeek.Shared.csproj" \
            --configuration Release \
            --output ./artifacts \
            --no-build
            
      - name: "Upload Build Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: shared-library-package
          path: ./artifacts/
          retention-days: 30

      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          config: .github/config/slack.yml
          channel: "#development"
          message: |
            Shared Library Build ${{ job.status }}
            Tests: ${{ needs.test.outputs.test-status }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
        if: always()