name: MeatGeek Deploy Shared Infra
on:
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/shared-resources.yml"
      - "shared/deploy/*"
      - "shared/build/build-deploy-resources.yaml"

jobs:
  deploy-shared-resources:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.SHARED_RG }}
          template: ./shared/deploy/shared.bicep
          parameters:
            kvName=${{ secrets.SHARED_KV }} objectId=${{ secrets.STEVE_OBJECT_USER_ID }}
            cosmosAccountName=${{ secrets.SHARED_COSMOS }}
            cosmosDatabaseName=${{ secrets.SHARED_COSMOS }}
            sessionsContainerName=${{ secrets.SESSIONS_COSMOS_COLLECTION_NAME }}
            sessionsPartition=${{ secrets.SESSIONS_COSMOS_PARTITION_PATH }}
            iotContainerName=${{ secrets.IOT_COSMOS_COLLECTION_NAME }}
            iotPartition=${{ secrets.IOT_COSMOS_PARTITION_PATH }}
          # additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
